In [15]:
#Importing packages
import random 
import numpy as np
import pandas as pd 
import matplotlib as plt

In [16]:
#Patient Record list to store the dictionaries of patient information
patient_record = []

In [17]:
#Function for Enter Patient Information
def enter_patient_info():
    print("Enter Patient Information:")
    initial_service_date = input("Date of Service (MM-DD-YYYY): ")
    patient_id = input("Patient ID#: ")
    name = input("Name: ").upper()
    sex = input("Sex (M/F): ").upper()
    age = input("Age: ")
    race = input("Race/Ethnicity: ").upper()
    prev_opioid_type = input("Previous Opioid Use Type: ").upper()
    initial_methadone_dose = int(input("Methadone Dose (mg): "))
    
    #Adding inputs to dictionary
    patient_info = {
        "Patient ID": patient_id,
        "Name": name,
        "Sex": sex,
        "Age": age,
        "Race/Ethnicity": race,
        "Previous Opioid Use Type": prev_opioid_type,
        "Date of Service": initial_service_date,
        "Methadone Dose (mg)": initial_methadone_dose,
    }
    patient_record.append(patient_info)
    print("Patient {} information is added/updated successfully.".format(name))  #need to put before return in order to print
    return

In [4]:
#Function to append patient's methadone dose and date of service
def update_methadone_dose():

    #asks user for input 
    patient_id = input("Enter Patient ID: ")
    new_date = input("Enter Date of Service (MM-DD-YYYY): ")
    new_dose = input("Enter Methadone Dose (mg): ")
    
    #makes sure dose is written as an integer
    try:
        new_dose = int(new_dose)
    except ValueError:
        print("Invalid dose entered. Please enter a numeric value.")
        return
    
    #finds patient record
    patient_found = False
    for record in patient_record:
        if record["Patient ID"] == patient_id:
            patient_found = True
            
            #'date of service' and 'methadone dose' are lists
            if not isinstance(record["Date of Service"], list):
                record["Date of Service"] = [record["Date of Service"]]
            if not isinstance(record["Methadone Dose (mg)"], list):
                record["Methadone Dose (mg)"] = [record["Methadone Dose (mg)"]]
            
            #to append new date and dose
            record["Date of Service"].append(new_date)
            record["Methadone Dose (mg)"].append(new_dose)
            print(f"Patient ID {patient_id} updated successfully.")
            break
    
    if not patient_found:
        print(f"Patient ID {patient_id} not found.")

In [18]:
#Look up patient record
def lookup():
    patient_id = input("Enter Patient ID: ")
    patient_found = False
    for record in patient_record: 
        if record ["Patient ID"] == patient_id:
            print(record)
            patient_found = True
            break
    if not patient_found: 
        print("Patient not found.")

In [6]:
#Function for the input prompt/welcome screen
def intro_prompt():
    while True:
        print("Welcome!")
        print("1. Enter Patient Information")
        print("2. Update Patient's Methadone Dose")
        print("3. Look Up Patient Information")
        print("4. Exit")

        choice = input("Please choose an option: ")

        if choice == "1":
            enter_patient_info()
        elif choice == "2":
            update_methadone_dose()
        elif choice == "3":
            lookup()
        elif choice == "4":
            print("Goodbye.")
            break
        else:
            print("Please enter a valid option.")
            break
intro_prompt()

Welcome!
1. Enter Patient Information
2. Update Patient's Methadone Dose
3. Look Up Patient Information
4. Exit

Please choose an option:  4

Goodbye.

In [19]:
patient_record

[]

In [20]:
#Turning Patient Record List to DataFrame

df = pd.DataFrame(patient_record)
df

Empty DataFrame
Columns: []
Index: []

In [21]:
df.to_csv('dataset.csv')
df

Empty DataFrame
Columns: []
Index: []

In [23]:
# Read the CSV file into a new DataFrame
 
df = pd.read_csv('dataset.csv')
df

,Patient ID,Name,Sex,Age,Race/Ethnicity,Previous Opioid Use Type,Date of Service,Methadone Dose (mg)
0,1,"Heath, Mason",m,23,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...","[40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 4..."
1,2,"Greene, Raegan",m,21,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
2,3,"Duarte, Billy",m,25,hispanic,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
3,4,"Rose, Katherine",f,44,hispanic,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
4,5,"Franklin, Cyrus",m,43,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
5,6,"Hunter, Dale",m,18,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
6,7,"Estrella, Amanda",f,22,hispanic,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
7,8,"Howard, Zane",m,41,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
8,9,"Lindsey, Miranda",f,26,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
9,10,"Flores, Matthew",m,27,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
10,11,"Tucker, Arthur",m,43,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
11,12,"Martinez, Julia",m,42,hispanic,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
12,13,"Gibbs, Sharae",f,40,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
13,14,"Harris, Lilianna",f,29,black,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
14,15,"Ramos, Alberto",m,33,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
15,16,"Nikolaos, Giannis",m,39,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
16,17,"Paracha, Kalif",m,35,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
17,18,"Rogers, Alex",m,29,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
18,19,"Sergio, Ottaviano",m,31,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
19,20,"Charikleia, Ouida",f,30,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
20,21,"Rivers, Elisa",f,32,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
21,22,"Nunez, David",m,42,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
22,23,"Davide, Michele",m,44,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
23,24,"Bender, Alexis",m,28,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
24,25,"Agbere, Affo",m,41,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
25,26,"Lee, Isabelle",f,40,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
26,27,"Bowers, Kylo",m,37,other,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
27,28,"Curtis, William",m,39,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
28,29,"Bruce, Annalise",f,43,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
29,30,"Conway, Aaron",m,41,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
30,31,"Robinson, John",m,54,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
31,32,"Barnett, Alexia",f,53,other,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
32,33,"Pena, Jack",m,54,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
33,34,"Aguilar, Patrick",m,48,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
34,35,"Gonzales, Ryan",m,49,hispanic,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
35,36,"Duva, Benjamin",m,45,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
36,37,"Wiley, Kimberly",f,51,white,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
37,38,"Marks, Bennet",m,50,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
38,39,"McCarthy, Michael",m,48,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
39,40,"Cervantes, Javier",m,53,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
40,41,"Parra, Immanuel",m,55,hispanic,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
41,42,"Acevedo, Owen",m,59,hispanic,oxycodone,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
42,43,"Quintana, Israel",m,63,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
43,44,"Ramirez, Juan",m,58,hispanic,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
44,45,"Roman, Nathanial",m,56,white,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
45,46,"Escobar, Anne",f,60,hispanic,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
46,47,"Howard, Dante",m,57,black,heroin,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
47,48,"Gregory, Miles",m,58,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
48,49,"Barry, Lia",f,60,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN
49,50,"Fitzgerald, Elena",f,59,white,fentanyl,"['11-01-2024', '11-02-2024', '11-03-2024', '11...",NaN